// Generate TikZ figures (figures/*.tex) for paper.tex from results/.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const tsv = f => readFileSync(new URL(`./results/${f}`, import.meta.url), 'utf8').trim().split('\n').map(l => l.split('\t'));
const final = JSON.parse(readFileSync(new URL('./results/final.json', import.meta.url)));
mkdirSync(new URL('./figures/', import.meta.url), { recursive: true });
const out = (name, body) => writeFileSync(new URL(`./figures/${name}.tex`, import.meta.url),
  `% generated by make_figs.mjs\n\\resizebox{\\columnwidth}{!}{\\begin{tikzpicture}[font=\\footnotesize]\n${body}\\end{tikzpicture}}\n`);
const f3 = v => v.toFixed(3);
const lg = Math.log2;

// Log-log (or lin) frame with gridlines and tick labels.
function frame({ W, H, x, y, xticks, yticks, xlabel, ylabel }) {
  let t = '';
  for (const [v, l] of yticks) t += `\\draw[gray!25] (0,${f3(y(v))}) -- (${W},${f3(y(v))}); \\node[left] at (0,${f3(y(v))}) {${l}};\n`;
  for (const [v, l] of xticks) t += `\\draw[gray!25] (${f3(x(v))},0) -- (${f3(x(v))},${H}); \\node[below] at (${f3(x(v))},0) {${l}};\n`;
  t += `\\draw (0,0) rectangle (${W},${H});\n\\node at (${W / 2},-0.7) {${xlabel}};\n\\node[rotate=90] at (-1.25,${H / 2}) {${ylabel}};\n`;
  return t;
}
const line = (style, pts) => `\\draw[${style}] plot coordinates {${pts.map(([a, b]) => `(${f3(a)},${f3(b)})`).join(' ')}};\n`;
const label = (style, a, b, text) => `\\node[${style}] at (${f3(a)},${f3(b)}) {${text}};\n`;
const bitsTicks = [[1, '1k'], [16, '16k'], [256, '256k'], [4096, '4M'], [32768, '32M']];

// 1. Speedup vs size ---------------------------------------------------------
{
  const W = 6.6, H = 4.6, x = v => (lg(v) + 2) / 17.2 * W, y = v => (lg(v) - lg(0.05)) / (lg(6) - lg(0.05)) * H;
  const e2e = tsv('e2e.tsv').slice(1), old = tsv('old.tsv').slice(1), v8 = Object.fromEntries(final.map(r => [r.n, r.v8]));
  let t = frame({ W, H, x, y, xticks: bitsTicks, yticks: [0.1, 0.25, 0.5, 1, 2, 4].map(v => [v, `$${v}\\times$`]),
    xlabel: 'operand size (bits, log)', ylabel: 'speedup vs V8 (log)' });
  t += `\\draw[black,thick] (0,${f3(y(1))}) -- (${W},${f3(y(1))});\n` + label('anchor=south west', 0, y(1), 'V8 = $1\\times$');
  t += line('blue,very thick', final.map(r => [x(r.n / 32), y(r.v8 / r.auto)]));
  t += line('gray,thick', e2e.map(c => [x(c[0] / 32), y(+c[6])]));
  t += line('gray,dashed', old.map(c => [x(c[0] / 32), y(v8[c[0]] / +c[1])]));
  t += label('blue,anchor=west', x(0.3), y(3), 'WASM kernel') + label('gray!70!black,anchor=west', x(150), y(1.2), 'WASM end-to-end')
    + label('gray!70!black,anchor=west', x(0.3), y(0.13), 'previous WASM Karatsuba');
  out('speedup', t);
}

// 2. Time vs size (scaling) --------------------------------------------------
{
  const W = 6.6, H = 4.8, x = v => (lg(v) + 2) / 17.2 * W, y = v => (Math.log10(v) + 1.7) / 8.7 * H;
  let t = frame({ W, H, x, y, xticks: bitsTicks,
    yticks: [[0.1, '0.1\\,\\textmu s'], [10, '10\\,\\textmu s'], [1000, '1\\,ms'], [1e5, '100\\,ms'], [1e7, '10\\,s']],
    xlabel: 'operand size (bits, log)', ylabel: 'time per multiply (log)' });
  t += `\\draw[gray,densely dotted] (${f3(x(96))},0) -- (${f3(x(96))},${H}) node[below left,align=right,font=\\scriptsize] {V8 switches\\\\to its FFT};\n`;
  t += line('gray,thick', final.map(r => [x(r.n / 32), y(r.v8)]));
  t += line('gray!60,thick,dashed', final.map(r => [x(r.n / 32), y(r.kara)]));
  t += line('blue,very thick', final.map(r => [x(r.n / 32), y(r.fft)]));
  const lx = x(0.3), ly = y(3e6);
  t += `\\fill[white] (${f3(lx - 0.05)},${f3(ly - 1.25)}) rectangle (${f3(lx + 3.1)},${f3(ly + 0.25)});\n`;
  t += `\\draw[blue,very thick] (${f3(lx)},${f3(ly)}) -- +(0.4,0);\n` + label('blue,anchor=west', lx + 0.45, ly, 'WASM FFT: $k{=}1.08$');
  t += `\\draw[gray,thick] (${f3(lx)},${f3(ly - 0.4)}) -- +(0.4,0);\n` + label('gray!70!black,anchor=west', lx + 0.45, ly - 0.4, 'V8: $k{=}1.64 \\to 1.18$');
  t += `\\draw[gray!60,thick,dashed] (${f3(lx)},${f3(ly - 0.8)}) -- +(0.4,0);\n` + label('gray!60!black,anchor=west', lx + 0.45, ly - 0.8, 'WASM Karatsuba: $k{=}1.65 \\to 1.59$');
  t += label('anchor=west,font=\\scriptsize,gray!70!black', lx, ly - 1.1, '($k$ below / above 64\\,kbit)');
  out('scaling', t);
}

// 3. Rounding error vs digit size ---------------------------------------------
{
  const rows = tsv('errsweep.tsv').slice(1).filter(c => c[5] === 'rand');
  const W = 6.6, H = 4.6, x = b => (b - 11.5) / 11 * W, y = v => (Math.log10(Math.max(v, 1e-8)) + 7.3) / 7.3 * H;
  let t = frame({ W, H, x, y, xticks: [12, 14, 16, 18, 20, 22].map(b => [b, String(b)]),
    yticks: [[1e-7, '$10^{-7}$'], [1e-5, '$10^{-5}$'], [1e-3, '$10^{-3}$'], [0.1, '$0.1$']],
    xlabel: 'bits per FFT digit', ylabel: 'max rounding error (log)' });
  t += `\\draw[black,thick] (0,${f3(y(0.5))}) -- (${W},${f3(y(0.5))}) node[pos=0.5,above] {0.5: rounding fails};\n`;
  t += `\\draw[black,dashed] (0,${f3(y(0.375))}) -- (${W},${f3(y(0.375))});\n`;
  const sizes = [...new Set(rows.map(c => c[0]))];
  const name = n => ({ 1024: '1K', 16384: '16K', 262144: '256K', 1048576: '1M' })[n];
  sizes.forEach((n, i) => {
    const op = 35 + 65 * i / (sizes.length - 1);
    for (const bal of ['1', '0']) {
      const pts = rows.filter(c => c[0] === n && c[4] === bal).map(c => [x(+c[1]), y(+c[6])]);
      t += line(bal === '1' ? `blue!${op},thick` : `gray!${op},thick,dashed`, pts);
    }
    const b = rows.filter(c => c[0] === n && c[4] === '1');
  });
  const ex = x(17.6), ey = y(3e-6);
  t += `\\draw[blue,thick] (${f3(ex)},${f3(ey + 0.4)}) -- +(0.4,0);\n` + label('anchor=west', ex + 0.45, ey + 0.4, 'balanced digits');
  t += `\\draw[gray,thick,dashed] (${f3(ex)},${f3(ey)}) -- +(0.4,0);\n` + label('anchor=west', ex + 0.45, ey, 'unsigned digits');
  t += label('anchor=west,font=\\scriptsize,align=left', ex, ey - 0.5, 'darker = larger operand\\\\(1K, 16K, 256K, 1M limbs)');
  out('error', t);
}

// 4. Optimisation ladder at 1M limbs -----------------------------------------
{
  const steps = [['radix-2, no bit-reversal', 206], ['budget 56, balanced', 114], ['radix-4 passes', 122],
    ['vectorised round/residues', 99], ['derived twiddles', 81], ['half-size inverse', 73]];
  const V8 = 304, W = 5.2, bh = 0.45, x = v => v / 330 * W;
  let t = '';
  steps.forEach(([s, ms], i) => {
    const yy = -i * 0.65;
    t += `\\fill[blue!${40 + 10 * i}] (0,${f3(yy)}) rectangle (${f3(x(ms))},${f3(yy + bh)});\n`;
    t += label('anchor=east', -0.1, yy + bh / 2, s) + label('anchor=west', x(ms) + 0.05, yy + bh / 2, `${ms} ms (${(V8 / ms).toFixed(1)}$\\times$)`);
  });
  const ybot = -(steps.length - 1) * 0.65 - 0.2;
  t += `\\draw[black,thick,dashed] (${f3(x(V8))},${f3(ybot)}) -- (${f3(x(V8))},0.8) node[above] {V8: ${V8} ms};\n`;
  t += `\\draw (0,${f3(ybot)}) -- (0,0.8);\n`;
  out('ladder', t);
}

// 5. End-to-end cost breakdown (share of V8 time) -----------------------------
{
  const rows = tsv('e2e.tsv').slice(1).filter(c => +c[0] >= 256);
  const W = 6.6, H = 4.2, bw = W / rows.length, ymax = 3.2, y = v => v / ymax * H;
  let t = '';
  for (const v of [0.5, 1, 1.5, 2, 2.5, 3]) t += `\\draw[gray!25] (0,${f3(y(v))}) -- (${W},${f3(y(v))}); \\node[left] at (0,${f3(y(v))}) {${v}};\n`;
  rows.forEach((c, i) => {
    const v8 = +c[1], parts = [[+c[2], 'gray!50'], [+c[3], 'blue!70'], [+c[4], 'gray!80']];
    let acc = 0; const x0 = i * bw + 0.08, x1 = (i + 1) * bw - 0.08;
    for (const [v, col] of parts) { t += `\\fill[${col}] (${f3(x0)},${f3(y(acc))}) rectangle (${f3(x1)},${f3(y(acc + v / v8))});\n`; acc += v / v8; }
    const bits = c[0] * 32 / 1024;
    if (i % 2 === 0) t += label('below,font=\\scriptsize', (x0 + x1) / 2, 0, bits >= 1024 ? `${bits / 1024}M` : `${bits}k`);
  });
  t += `\\draw[black,thick] (0,${f3(y(1))}) -- (${W},${f3(y(1))}) node[pos=0.97,above left] {V8 time};\n`;
  t += `\\draw (0,0) rectangle (${W},${H});\n\\node at (${W / 2},-0.7) {operand size (bits)};\n\\node[rotate=90] at (-1.0,${H / 2}) {time / V8 time};\n`;
  t += `\\fill[gray!50] (${W - 2.3},${H - 0.35}) rectangle +(0.25,0.2); \\node[anchor=west,font=\\scriptsize] at (${W - 2.0},${H - 0.25}) {BigInt$\\to$limbs};\n`;
  t += `\\fill[blue!70] (${W - 2.3},${H - 0.7}) rectangle +(0.25,0.2); \\node[anchor=west,font=\\scriptsize] at (${W - 2.0},${H - 0.6}) {WASM multiply};\n`;
  t += `\\fill[gray!80] (${W - 2.3},${H - 1.05}) rectangle +(0.25,0.2); \\node[anchor=west,font=\\scriptsize] at (${W - 2.0},${H - 0.95}) {limbs$\\to$BigInt};\n`;
  out('e2e', t);
}

// 6. FFT stage profile (share of total) ---------------------------------------
{
  const lines = readFileSync(new URL('./results/prof.txt', import.meta.url), 'utf8').trim().split('\n');
  const stages = [['load', 'gray!40'], ['fwd', 'blue!80'], ['pointwise', 'gray!60'], ['inv', 'blue!45'], ['extract', 'gray!80'], ['residues', 'orange!60']];
  const W = 5.6; let t = '';
  lines.forEach((l, i) => {
    const kv = Object.fromEntries(l.split(' ').map(p => p.split('=')));
    const yy = -i * 0.75, full = +kv.full;
    let acc = 0;
    for (const [s, col] of stages) { const w = +kv[s] / full * W; t += `\\fill[${col}] (${f3(acc)},${yy}) rectangle (${f3(acc + w)},${yy + 0.5});\n`; acc += w; }
    t += `\\fill[gray!15] (${f3(acc)},${yy}) rectangle (${W},${yy + 0.5});\n`;
    const n = +kv.n; t += label('anchor=east', -0.1, yy + 0.25, `${n >= 1 << 20 ? '1M' : n / 1024 + 'K'} limbs`);
  });
  const names = ['load digits', 'forward FFT', 'pointwise', 'inverse (N/2)', 'round+carry', 'residue check', 'other'];
  const cols = [...stages.map(s => s[1]), 'gray!15'];
  names.forEach((nm, i) => { const xx = (i % 3) * 2.0 - 0.6, yy = -lines.length * 0.75 + 0.1 - Math.floor(i / 3) * 0.35;
    t += `\\fill[${cols[i]}] (${xx},${yy}) rectangle +(0.22,0.2); \\node[anchor=west,font=\\scriptsize] at (${xx + 0.25},${yy + 0.1}) {${nm}};\n`; });
  t += `\\foreach \\p in {0,25,50,75,100} {\\node[font=\\scriptsize] at (${W}*\\p/100,0.75) {\\p\\%};}\n`;
  out('profile', t);
}
console.log('wrote figures/*.tex');
